# TensorFlow Syntax Basics



In [0]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.12.0


In [0]:
hello = tf.constant("Hello")

In [0]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [8]:
print(result)

b'HelloWorld'


In [0]:
a = tf.constant(10)

b = tf.constant(20)

In [10]:
type(a)

tensorflow.python.framework.ops.Tensor

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
  result = sess.run(a+b)
  
result

30

In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4),10)

In [0]:
myzeros = tf.zeros((4,4))

In [0]:
myones = tf.ones((4,4))

In [0]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [0]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [0]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [0]:
sess = tf.InteractiveSession()

In [21]:
for op in my_ops:
  print(sess.run(op))
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.67860025 -1.1026555   0.67144454  0.6425024 ]
 [-1.8831028   0.487426   -0.68186563 -1.1809195 ]
 [-0.94911695 -0.52052236 -0.96944994 -0.8984489 ]
 [-0.86420494  1.2146919   0.5202029  -0.5443995 ]]


[[0.43222618 0.83503795 0.618448   0.89780176]
 [0.92482567 0.65697587 0.37899292 0.21406364]
 [0.2907169  0.8710842  0.5558418  0.66390526]
 [0.6132009  0.7770976  0.2967869  0.23094809]]




In [0]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [23]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([ [10], [100]])

In [25]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [27]:
sess.run(result)

array([[210],
       [430]], dtype=int32)